### ISSUE TITLE
SMARTS matching failure

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1188]
Hi,

I'm using the C++ API of Open Babel 2.3.1, and the SMARTS matching is not behaving as I would expect. If I read in the following molecule:

CC(=O)[NH]

and then look for this SMARTS pattern:

[ND1H1][#6]

the parser fails to match it. Interestingly, it does find a match for [ND2H1][#6]. I'm not sure whether the problem lies in the SMILES parsing (the molecule is a radical), or the matcher itself. Daylight correctly finds the matching atom.

Any further questions, please contact me at paul dot mortenson _at_ astx dot com

Thanks to all for your continued work!

Paul Mortenson

Reported by: *anonymous

**Comment by baoilleach** [comment]
Sorry for the delay :-) Fixed by #1576. We now "Do it like Daylight", and don't 'expand' hydrogens inside square brackets.

obabel -:CC(=O)N -:CC(=O)[NH] -:CC(=O)[NH2] -s [ND1] -osmi
CC(=O)N
CC(=O)[NH]
CC(=O)N

obabel -:CC(=O)N -:CC(=O)[NH] -:CC(=O)[NH2] -s [Nh2] -osmi
CC(=O)N
CC(=O)N

obabel -:CC(=O)N -:CC(=O)[NH] -:CC(=O)[NH2] -s [Nv2] -osmi
CC(=O)[NH]
