### ISSUE TITLE
Python SWIG - Error when calling OBRotorList::Init 

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1341]
Hello everyone,

I think I've found a bug in the Python SWIG interface.
I tried to use the Init method of OBRotorList and received the following error:
TypeError: in method 'OBRotorList_Init', argument 2 of type 'std::string &'

Below I paste the call of the function, showing how it is in my code:
rbonds = openbabel.OBRotorList()
temp = tempfile.NamedTemporaryFile(mode='w+t')
	try:
		temp.write("[!$(*#*)&!D1]-!@[!$(*#*)&!D1] 1 2 3 4 60.0 -60.0 180.0 160.0 -160.0 90.0 -90.0 120.0 -120.0")
		print temp.name
		rbonds.Init(temp.name) # bug in openbabel 2.3.2 -- problem in swig interface
	finally:
		temp.close()	

Looking for a solution I found that the problem may be in the interface, in which an "%include std_string.i" may be missing (see, e.g., http://stackoverflow.com/questions/6090976/swig-python-c-typeerror-in-method-geodatabase-open-argument-2-of-type)

This one may be easy to fix, but unfortunately I have no knowledge in SWIG or OpenBabel to create a patch for it.

Best Regards,
Henrique.

Reported by: hmcezar

Original Ticket: [openbabel/bugs/962](https://sourceforge.net/p/openbabel/bugs/962)

**Comment by serval2412** [comment]
I could reproduce this with master sources updated yesterday on Debian x86-64.
However,  ./scripts/openbabel-python.i already contains %include "std_string.i" at line 99
So the pb comes from another thing.

**Comment by serval2412** [comment]
With this patch:
`diff --git a/scripts/openbabel-python.i b/scripts/openbabel-python.i
index cc686c90..a7c284eb 100644`
`--- a/scripts/openbabel-python.i`
`+++ b/scripts/openbabel-python.i`
`@@ -344,6 +344,7 @@ OBMol.BeginResidues = OBMol.EndResidues = OBMol.BeginResidue = OBMol.EndResidue`
 
 ` // Ignore shadowed method `
  `%ignore OpenBabel::OBRotor::GetRotAtoms() const; `
 `+%apply std::string& INPUT { std::string &fname } // Required for OBRotorList.Init `
 ` %include <openbabel/rotor.h> `
 ` %ignore OpenBabel::Swab; `
 ` %include <openbabel/rotamer.h> `

I don't get the initial error but:
`*** Open Babel Warning  in Init
  Cannot initialize database '/tmp/tmpgtfUGE' which may cause further errors.
`
I don't know if it's another problem or if it's because the proposed patch is wrong.
Any thoughts?

**Comment by serval2412** [comment]
I thought about this patch because "Init" method from OBRotorList initializes a struct "_rr" (type OBRotorRules), see openbabel/rotor.h
According to http://www.swig.org/Doc1.3/Library.html, a typemap must be defined in this case.

**Comment by baoilleach** [comment]
We should replace all instances of functions in our API that take a "&std::string" to instead take "const char *". Could you make that fix instead here - this should presumably also make the error message go away.

Regarding the original problem, using temporary files in Python is as straightforward as the OP might think; there are various ways this can go wrong. I would focus on whether the original code works without reference to temporary files, i.e. if you just create a file, write to it and close it. In the original code, the file might still be empty as Python may not have created or written it before the .close() statement.

Am happy to pursue if you want to bounce it over to me.

**Comment by ghutchis** [comment]
My count inside includes/openbabel is 318 lines. That includes some documentation, but seems managable.
