### ISSUE TITLE
OBDotNet : The type initializer for 'OpenBabel.openbabel_csharpPINVOKE' threw an exception. Unable to load DLL 'openbabel_csharp'

### ISSUE THREAD

**Issue by openbabel-bot** [openbabel/openbabel#1347]
Hi there,

I have developed a web application in .NET C# code using OBDotNet. My OS is Windows 7, 64 bit.The version of Open Babel I am using, is OpenBabel-2.3.2.
Its working fine when I run application in Microsoft Visual studio. But after publishing my application and hosting it on IIS, when I run the application, it is throwing exception. I am attaching the same error log file for your reference.
Please help.

Thanks
Pradeep

Reported by: pradeepv67

Original Ticket: [openbabel/bugs/968](https://sourceforge.net/p/openbabel/bugs/968)

**Comment by abrechts** [comment]
This is a long standing issue. The problem is that no x64 version of OBDotNet.dll is available. This is extremely limiting, since this forces you to target all .NET projects referencing OBDotNet.dll to the x86 platform exclusively - otherwise you get the type initializer errors as described by the op. Providing an x64 version of the dll would solve these issues permanently.

**Comment by baoilleach** [comment]
There is a 64-bit version.

**Comment by abrechts** [comment]
Ok, so I must have been confused by the wiki page of the previous version, which states that it is x86 only and describes the resulting limitations:
http://openbabel.org/docs/dev/UseTheLibrary/CSharp.html.

I assume that the x64 version is part of the the x64 OpenBabel installation then.

**Comment by baoilleach** [comment]
Our documentation needs updating. Apologies.

**Comment by barbarrossazzy** [comment]
anybody who solve the issues?Now i meet the same problem i need help.

**Comment by barbarrossazzy** [comment]
Anybody who solve the issues?Now i meet the same problem. I need help.
