### ISSUE TITLE
Procedure for adding regression tests

### ISSUE THREAD

**Issue by mj-harvey** [openbabel/openbabel#165]
Hi,

Could someone give me a quick outline of the procedure for adding test cases, please?

Matt

**Comment by baoilleach** [comment]
(Note to self: add to docs)

Add a small number of tests
=====================

1. For each test you want to add, add a new switch statement target (the "test ID") at the bottom of regressions.cpp. To avoid merge problems it may be a good idea to choose test IDs in a particular unique range, e.g. values starting at 6200, rather than the next available integer.
2. The switch statement should call a function that actually carries out the test. Appropriate code is described below.
3. Edit the line starting with "set (regression_parts" in :file:`tests/CMakeLists.txt` to include your new test target integers.
4. Rebuild the project. Now it should be possible to run your test directly with "testrunner regression NN" where NN is the test ID. It should also be run automatically by "make test".

Test code
=======
Need to write this up. For the moment, check out existing tests. You can use OB_ASSERT, or printf("Fail\n"), to fail a test. The best tests fail without the patch, and pass afterwards. Even better tests will cover a larger range of behaviour to ensure that it keeps working.
