### ISSUE TITLE
Compatibility with NMReDATA SDF tags

### ISSUE THREAD

**Issue by djeanner** [openbabel/openbabel#1935]
This is a feature request

** BACKGROUNG **
The NMReDATA Initiative  introduced the use .sdf files to include NMR assignment data. ( nmredata.org/wiki/NMReDATA_tag_format ).
One of the tag of the .sdf file makes the link between the atom number in the molblock and the labels used for the NMR assignement. When adding or removing H (or when anything else changing the oder of the atom in the structure), the <NMREDATA_ASSIGNMENT> should be updated so that the reference to the atoms is updated. Doing this would allow the use of open babel for sdf files including NMR DATA

** Request **
Do you think is is possible to include in babel a function that would update the <NMREDATA_ASSIGNMENT> tag when .sdf files with NMReDATA are identified ? It would be very usefull for the community building tools to manipulate these files.

** Example of relevant file **
The attached document is a typical file .sdf containing NMReDATA that would need addition of H before going "3D". It could be done with in two steps using babel and obgen.

** Structure of the tag **
The format of the <NMREDATA_ASSIGNMENT> tag is the following (see example below). Fields are separated by comma, the end-of-line is "\" and ASCII-10 should be ignored when reading the tag. The first field is the NMR-label, the second is the chemical shift, all the others list the atoms the label corresponds to (may refer to more than one in case of symetry). When refering to an implicit hydrogen, a "H" is placed before the atom number it is attached to.

  <NMREDATA_ASSIGNMENT>
1, 34.5669, 1\\
2, 23.1445, 2\\
H3, 1.1301, H3\

** What to do when make H explicit**
-"H3" (see above) would be replace with the atom number of the newly introduced H. 

-When the H of a CH2 is made explicit we may have to add a flag in the  <NMREDATA_ASSIGNMENT> tag to signal that the two added H were arbitrarily placed. I will give more details about this case later...

** what to do when changin the oder of the atom in the molblock **
-The atom number should be updated in the <NMREDATA_ASSIGNMENT> tag.

[Menthol_explicit_ax_eq_full_assignments_1.nmredata.sdf.zip](https://github.com/openbabel/openbabel/files/2901169/Menthol_explicit_ax_eq_full_assignments_1.nmredata.sdf.zip)

**Comment by baoilleach** [comment]
We won't be changing our own Add/RemoveHydrogens to do this. The functionality you describe is outside the scope of Add/RemoveHydrogens() in a general purpose cheminformatics library. However, the required functionality can easily be implemented client-side by providing wrappers around the required functionality, e.g. NMRDATA::Add/RemoveHydrogens(OBMol*) which would call the relevant OBMol function and then have some extra code to update the sdf field.

I should point out that this problem could have been entirely avoided by using a tag that didn't depend on atom order, but rather was based on intrinsic properties of the SDF file format, for example, involving atom labels rather than atom orders. These are invariant to operations on the molecule such as adding/removing hydrogens or rearranging the atoms in any other way.

**Comment by baoilleach** [comment]
An alternative would be to write a function that parsed the field and stored the information as atom data. These are preserved during modification. Then you just need a second function that turns the atom data back into the sdf tag.

**Comment by djeanner** [comment]
I thank you very much for the suggestion.
Damien
