### ISSUE TITLE
Tmol to inchikey conversion fails in commandline Open Babel 3.0.0 

### ISSUE THREAD

**Issue by tobigithub** [openbabel/openbabel#2063]
The LINUX commandline version (Open Babel 3.0.0 -- Oct 19 2019 -- 15:23:09) can not convert tmol files to inchikey. The tmol file was created using openbabel (with low caps element symbols).

propane.tmol
```
$coord
    2.02871026746136      0.00016096463521      0.09107555338913      c
    4.89930048862534      0.04854048717752      0.11762901668325      c
    5.90748259036722      2.39968480185142      1.42109501042332      c
    1.34938005428171     -1.70839952555376     -0.85607794562344      h
    1.26886043300105      1.63876093409995     -0.91749501051641      h
    1.26913011943130      0.01286165737104      2.01525659069294      h
    5.60784060607910     -0.01912944162451     -1.82662623368806      h
    5.60811561474418     -1.63627235546083      1.09011360983431      h
    5.27020211768512      4.11415935313881      0.45463376946747      h
    7.97573431608248      2.39090324576822      1.41600146807434      h
    5.27052201944755      2.48814711866854      3.38732271725103      h
$end
```

Error openbabel commandline  version (LINUX):
````
 obabel -itmol propane.tmol -oinchikey
==============================
*** Open Babel Warning  in InChI code
  #1 :Unknown element(s): *
==============================
*** Open Babel Error  in InChI code
  InChI generation failed
0 molecules converted
````
The GUI version (WIN) converts above molecule correctly to ATUOYWHBWRKTHZ-UHFFFAOYSA-N. 

When changing the elements to large caps, the command line (LINUX) version succeeds.

```
$coord
    2.02871026746136      0.00016096463521      0.09107555338913      C
    4.89930048862534      0.04854048717752      0.11762901668325      C
    5.90748259036722      2.39968480185142      1.42109501042332      C
    1.34938005428171     -1.70839952555376     -0.85607794562344      H
    1.26886043300105      1.63876093409995     -0.91749501051641      H
    1.26913011943130      0.01286165737104      2.01525659069294      H
    5.60784060607910     -0.01912944162451     -1.82662623368806      H
    5.60811561474418     -1.63627235546083      1.09011360983431      H
    5.27020211768512      4.11415935313881      0.45463376946747      H
    7.97573431608248      2.39090324576822      1.41600146807434      H
    5.27052201944755      2.48814711866854      3.38732271725103      H
$end

$ obabel -itmol propane.tmol -oinchikey
ATUOYWHBWRKTHZ-UHFFFAOYSA-N
````

**Comment by e-kwsm** [comment]
obabel f84536d804b4e2b530daf8831f264ea72a5cedf0 cannot treat lower-case symbols in CML and XYZ files as well. Not sure if this is intended or not.

**Comment by baoilleach** [comment]
We can add back support if necessary, but we shouldn't do it just because OB 2 did it unless it was the correct behavior. Support was lost because I tightened up the lookup from atomic symbol to atomic number. If a format wishes to handle additional symbols (like lowercase, or D, T, etc.) it must do it itself.

So, the question is...

Shouldn't the elements symbols be uppercase? That is, isn't Open Babel behaving correctly in rejecting this file. For example, what is the spec for a Turbomole input file? Does it allow/encourage lowercase symbols for the elements?

(Similarily CML and XYZ.)

**Comment by ghutchis** [comment]
@baoilleach - while Turbomole or other parsers should explicitly handle that, I also think that the detection of symbols should handle all cases. There are *many* non-standard files out there with CA = Ca or "c" instead of C. Policy has always been to "accept reasonable files" and "write standard-compliant".

So yes, IMHO this is a bug, to accept additional symbols (D, T in particular) as well as case-insensitive comparisons.

**Comment by baoilleach** [comment]
Fair enough. I'll sort it out.
