### ISSUE TITLE
`pip install` gets 2.4.1 instead of 3.0.0

### ISSUE THREAD

**Issue by berquist** [openbabel/openbabel#2067]
I think this is because the source from https://pypi.org/project/openbabel/2.4.1/#files was not uploaded for 3.0.0: https://pypi.org/project/openbabel/#files.

**Comment by baoilleach** [comment]
Which OS?

**Comment by berquist** [comment]
Both macOS and Arch Linux.

**Comment by baoilleach** [comment]
I don't know if @mcs07 is going to continue supporting this way of installing the bindings. Any particular reason you don't use the official route or use conda?

**Comment by baoilleach** [comment]
Given the silence, you'll have to use the 'officially supported' methods of installing the Python bindings, either conda or by building the bindings against a particular Python. Unfortunately, there's no way to tell pip to not install the earlier version. Of course, we would welcome help to maintain pip installing on Mac and Linux.

**Comment by berquist** [comment]
We are now using `conda` for part of our Travis CI pipeline, so this is less of an issue. PyPI is nice for those who don't want to use `conda`, and it is hard to version against the system install.

**Comment by TDI-tenderholt** [comment]
@baoilleach Any pointers for helping with maintenance for installing on Mac and Linux via pip? The docs / website are pretty out of date: http://openbabel.org/wiki/Main_Page. Is there a new home that's more up-to-date?

**Comment by mcs07** [comment]
Sorry for the slow reply. It's not too much trouble to put a new 3.0 package onto PyPI. @e-kwsm has already done most of the hard work in updating the `setup.py` script in #2060. Someone just needs to run `python setup.py sdist` in the `scripts/python` directory, then upload the result with `twine`.

However... there is a bug in the 3.0 release that means that the pip install process will fail to find the   OB include directory. This has since been fixed (#2059, @e-kwsm again, thanks!) but I would recommend against uploading the sdist until this fix is released (in 3.0.1?), otherwise it will just break `pip install...` for everyone who hasn't compiled the latest master from source.

Honestly, this is just the latest example of how unreliable it is to install via pip with a sdist that relies on pkgconfig to find OB and then run swig at install time. I would strongly recommend people use conda instead, which has none of these problems. If people are really keen on pip, a better solution would probably be to create binary wheel files like Noel does for Windows, but I have no experience with this.

**Comment by baoilleach** [comment]
For my part, if anyone creates a setup.py that is good to go against the
current release, I am happy to upload it. There is a test pypi server where
things can be tested.

**Comment by langner** [comment]
According to @mcs07 above, this should already be working. Is there any blocker here, besides uploading? I'm willing to test the package.

**Comment by baoilleach** [comment]
Just to follow up. @mcs07 stated that it wasn't working because the openbabel source had an error, not the setup.py. So we have had to wait until 3.1. I've just uploaded 3.1.1 to PyPi. Let me know if it works or not.
