### ISSUE TITLE
Fails to find the pre-installed coordgen-1.4.0 package

### ISSUE THREAD

**Issue by yurivict** [openbabel/openbabel#2214]
coordgen-1.4.0 (as installed from its GitHub repository https://github.com/schrodinger/coordgenlibs) installs these cmake files:
```
$ pkg info -l coordgenlibs | grep -i cmake
	/usr/local/lib/cmake/coordgen-config-release.cmake
	/usr/local/lib/cmake/coordgen-config.cmake
```

Yet, OpenBabel-3.1.1 doesn't find it.

**Comment by yurivict** [comment]
Here https://github.com/openbabel/openbabel/blob/master/cmake/modules/Findcoordgen.cmake#L34 your cmake scripts look for the file ```templates.mae``` that ```coordgenlibs``` doesn't install.

**Comment by yurivict** [comment]
Additionally: In case of ```WITH_COORDGEN=OFF``` the cmake message isn't adequate:

```-- Coordinate generation with Coordgen will NOT be supported. Please install Boost to enable Maestro formats.```

The reason that Coordgen is not supported is because this option was turned off.

**Comment by yurivict** [comment]
Related: https://github.com/schrodinger/coordgenlibs/issues/64

coordgenlibs seems to be broken because it fails to install the ```templates.mae``` file.

**Comment by jcbollinger** [comment]
I ran into this, too, and made the same diagnosis.  But I think the flaw is in OpenBabel.  As far as I can tell, coordgenlibs uses templates.mae only at build time, for source code generation, not at runtime, so there's no particular need for it to install the file.  Since OpenBabel does not appear to rely on that file directly, I see no reason why it should be checking for it at all.
