### ISSUE TITLE
Open Babel Error  in OpenBabel::OBBuilder::GetFragmentCoord Rigid fragment c1cccnc1 in rigid-fragments.txt has all zero coordinates

### ISSUE THREAD

**Issue by dalong12** [openbabel/openbabel#2332]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1
Operating system and version: win 10, python 3.8

## Expected Behavior
I want to convert the smi to 3D structure and save the mol in mol2 format. But the jupyter lab interface was restarted automatically after the code was executed with error information.

## Actual Behavior
the reported error is information below,
*** Open Babel Error  in OpenBabel::OBBuilder::GetFragmentCoord
  Rigid fragment c1cccnc1 in rigid-fragments.txt has all zero coordinates.

## Steps to Reproduce
from openbabel import pybel
mol = pybel.readstring("smi", "OC(C1=NC=CC=C1CC2=CC=C(C3CCC(S(=O)(NC)=O)CC3)C=C2)=O")
mol.make3D()

**Comment by nbehrnd** [comment]
For the moment, maybe an other way (running OpenBabel from the CLI / terminal / cmd.exe) equally suits your needs:

 `obabel -:'OC(C1=NC=CC=C1CC2=CC=C(C3CCC(S(=O)(NC)=O)CC3)C=C2)=O' --gen3d -omol2 -O output.mol2`

[test_conversion.zip](https://github.com/openbabel/openbabel/files/6045688/test_conversion.zip)

**Comment by StashOfCode** [comment]
@nbehrnd  this still does not really work :(

@dalong12 were you able to solve this issue?

**Comment by nbehrnd** [comment]
On occasion, requesting OpenBabel to generate the 2D structure in first place _as an intermediate_ then used for the 3D structure is a successful alternative.  Aiming to retain as much chemical information from the SMILES string as possible, I recommend the use of of the `.sdf` format for the intermediate step because (in contrast to e.g., `.xyz`) it equally contains what MDL coined as _connection table_ about which (and how) atoms are bound.

A) The more verbose approach consists of three distinct instructions to the CLI.  This documents each step by a permanent record.
`obabel -:'OC(C1=NC=CC=C1CC2=CC=C(C3CCC(S(=O)(NC)=O)CC3)C=C2)=O' --gen2d -osdf -O 2D.sdf`
`obabel -isdf 2D.sdf --gen3d -osdf -O 3D.sdf`
And, because you want to continue with the `.mol2` format
`obabel -isdf 3D.sdf -omol2 -O 3D.mol2`

B) The more condensed approach uses the intermediate output of one of the steps mentioned above as input for the subsequent step.  Thus, you start with the SMILES string to form the `.mol2` files without creation of intermediate permanent files.  Call OpenBabel with one line of instruction in the pattern of
`obabel -:'OC(C1=NC=CC=C1CC2=CC=C(C3CCC(S(=O)(NC)=O)CC3)C=C2)=O' --gen2d -osdf | obabel -isdf --gen3d -osdf | obabel -isdf -omol2 -O 3D_relayed.mol2`

The comparison of the two approaches reveals that coordinates in the `.mol2` files written differ from each other.  As shown, e.g. by vimdiff ([an introduction](https://www.tutorialspoint.com/vim/vim_diff.htm), but you may use a difference viewer of your preference), these differences however _do not_ affect the connection tables in the later part of the   `.mol2` files:

![diff_view](https://user-images.githubusercontent.com/19709084/114673269-878cbc00-9cf5-11eb-8cef-6c68f1e53f15.png)

Depending on the intended use of the `.mol2`, these differences may not be relevant to you.*)  Or, you use them anyway as a _starting point_ for further minimization with one of the force field options in OpenBabel or a third party program.

*) Simplified into the `.xyz` format, you may quantify the difference of the geometries, e.g. by a [Kabsch test](https://github.com/charnley/rmsd).

[test_run.zip](https://github.com/openbabel/openbabel/files/6309095/test_run.zip)

**Comment by StashOfCode** [comment]
Hi @nbehrnd ! Thanks for a detailed response. Initially i skipped all the molecules with these errors, but then i looked at what gets generated and saw this thing:
![image](https://user-images.githubusercontent.com/22925108/114953213-92179480-9e60-11eb-859c-89cbbd3e830b.png)

I then decided to switch to this library http://users.abo.fi/mivainio/balloon/index.php and it solved all of my issues. I haven't tried your last recommendation though.

**Comment by nbehrnd** [comment]
Your illustration above shows a completely different molecule (e.g., a bromine atom, thiazole ring).  Aside from this, and I admit, likely to be too slow for the conversion of batches of SMILES into `.sdf` (or other formats), I found [Jmol](http://jmol.sourceforge.net/) may be of help for such a conversion, provided the computer may reach to a server at [cactus.nci.nih.gov](https://cactus.nci.nih.gov/):

+ launch the program
+ similar to reading from a file, issue a command in pattern of `load smiles "c1ccccn1";` in Jmol's console
+ wait a sec (depends a bit on the internet connection)
+ as usual, the tentative 3D structure may be stored permanently, e.g., by `write "pyridine.sdf";` / minimized by the MMFF forcefield implementation in Jmol's toolkit.  Actually, the example below suggests, this already is possible for quite some time:

![Jmol](https://user-images.githubusercontent.com/19709084/115271360-c7580700-a12c-11eb-8330-6392855cfd34.png)

(Lack of dedicated volunteers with good knowledge of Java, JavaScript, and Linux contributes to the cause why Linux Debian 11 / bullseye still keeps this old, but known-to-work version in its repositories. The conversion shown still is possible, e.g. with the less old Jmol 14.31.32 released February 2021.)
