### ISSUE TITLE
smiles to fasta conversion 

### ISSUE THREAD

**Issue by shahik** [openbabel/openbabel#2359]
- [ Yes] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version:   2.4.1
Operating system and version:   Windows 10 

## Expected Behavior

   I tried canonical smiles, smi and smiles format to get a fasta file output with proper values. Note I am getting smiles from Chembl database. 

## Actual Behavior

>Unknown molecule 0 bp; generated with OpenBabel 2.4.1
## Steps to Reproduce

take any canonical smiles & convert to fasta 
COC(=O)c1ccc2c(c1)c1ccccc1n2CCCN1C[C@H](C)N[C@H](C)C1
--

**Comment by nbehrnd** [comment]
Consider an update of your installation of OpenBabel in first place.  Note, the current version 3.1.1 is available since May 2020.

Second, check the SMILES string.  An input of this string e.g., in the [PubChem Sketcher](https://pubchem.ncbi.nlm.nih.gov/edit3/index.html) yields an eight-membered ring with hydrogens bonding twice, right the ones next to the chirality indicators (`@` sign):

![sketcher](https://user-images.githubusercontent.com/19709084/115303973-d9996b80-a153-11eb-9d58-22eb9a0205f4.png)

**Comment by fredrikw** [comment]
In addition, quoting the Wikipedia page on FASTA format:

>  FASTA format is a text-based format for representing either nucleotide sequences or amino acid (protein) sequences, in which nucleotides or amino acids are represented using single-letter codes.

I don't think you can expect "...any canonical SMILES..." to be converted to FASTA.

**Comment by nbehrnd** [comment]
@fredrikw, @shahik  This lead me to type `obabel -L fasta` on the CLI.  At least OpenBabel (v. 3.1.0) as currently repackaged in Linux Debian 11/bullseye points to a apparently defunct web page, so the first reference will be the [wikipedia article](https://en.wikipedia.org/wiki/FASTA_format) mentioned.  I notice [FASTQ](https://en.wikipedia.org/wiki/FASTQ_format), perhaps a superset of FASTA introduced around the year 2000, isn't (yet) a format OpenBabel trades with.

**Comment by fredrikw** [comment]
But FASTQ is not a general chemistry format either so it wouldn't help at all in this case. What are you trying to do?

**Comment by nbehrnd** [comment]
I agree; the conversion FASTA -> SMILES would be possible only if
the structure to be converted could be described in FASTA in first
place.  But this «conversion» falls flat; because the motif of
carbazole isn't among the (essential) \alpha amino acids proteins are
built, it is not in FASTA's scope.

My point about FASTQ only was: perhaps there is a demand for a FASTQ
-> FASTA conversion, which need not to be a project for OpenBabel.
But these two formats are foreign to mine, and do not use either one.

**Comment by fredrikw** [comment]
Sorry @nbehrnd , I misstook you for the original poster...

**Comment by shahik** [comment]
thanks for the detailed reply. I have a collection of smiles string and trying to get fasta format for protein folding algorithm as input. I see babel does not have .seq format an alternative input to protein folding algos.

**Comment by fredrikw** [comment]
@shahik , do you have a collection of proteins as SMILES strings? What's the source for those?

**Comment by nbehrnd** [comment]
@shahik  I have no working knowledge of FASTA, nor protein folding;
conceptually, however, I suggest to check the following approach in
either OpenBabel, and RDKit. -- It could in / with either, or none.

+ There is a finite set of amino acids FASTA considers, each of them
  described by a single character.

+ Look up the SMILES strings for each of these amino acids.  Many
  chemicals, including amino acids, are described -- including SMILES
  and InChi -- in Wikipedia; these particular descriptors are
  mentioned in the top right / top left "biographic box" (depending
  if your script runs from left to right, or right to left).

+ With this dictionary in hand, check if your input SMILES structures
  may be fully described by this reference.  A potential pitfall is
  how these amino acids are described in terms of a charge
  (protonated / neuter amino group) in your reference SMILES about
  individual amino acids / in the SMILES string.

+ Identify if / how OpenBabel / rdkit may linearly "digest" the
  SMILES string, similar to reading the primary protein structure
  about the consecution of amino acids only, and iteratively state
  the single letter (FASTA) code.  (A dictionary-based string
  substitution would be more efficient and easier to maintain than
  20+ subsequent if-clauses.)  This is based for on RDKit's
  capability to identify structure pattern; Jan Jensen's beginner's
  tutorial [1] showcases this for using Python in Jupyter notebook
  about individual amino acids.

I speculate OpenBabel is not competitive to folding algorithms
specifically designed to work on large proteins because the underlying
implementation of MMFF is a force field for / about small molecules
with a few degrees of freedom only.  With what I retain from chem /
bio at grammar school, I equally assume one approach a protein folding
algorithm possibly probes is to start folding the protein right from
the moment when two amino acids form a dipeptide.  To await the long
AS sequence to be synthesized completely and then to form the
secondary / tertiary / quaternary structure would be computationally
much more demanding (optimizing all degrees of freedom at once);
equally, proteins curl up right after leaving the ribosome / entering
the cytoplasm for a better state (energy wise).

Stackexchange «matter modelling»,[2] while still in beta phase,
already allows to label questions with the tag «protein-folding», too.


[1] https://www.youtube.com/watch?v=ERvUf_lNopo
[2] https://mattermodeling.stackexchange.com/

**Comment by shahik** [comment]
Sorry, I am also unable to convert from fasta to pdb or smiles. What can I do?

**Comment by fredrikw** [comment]
I just tried to go from Fasta to SMILES as well and got a fully disconnected structure. This seems more like a bug, could you please report it as a new issue with example files and outputs?

**Comment by nbehrnd** [comment]
Without working knowledge about the `.fasta` format, I simply provided a sequence like `ATCG`, requested to OpenBabel to convert this into a joined SMILES string (`-j`, or `--join`) and to write a `.sdf` for visual inspection in Jmol, too.

The result is ambivalence.  For one, the result already looks «DNA-like» in a ladder-like motif:

![test](https://user-images.githubusercontent.com/19709084/116211601-831fc480-a733-11eb-8511-1cec5160032b.png)

For the other side, the output is about _two_ molecules instead of the single one I anticipated.

In the SMILES, this is marked by the dot laying on the floor; this syntax pattern is seen elsewhere, e.g., to describe co-crystals (presence of more than one molecule in a model, for example a remaining solvent molecule), too.  So I speculate, this is might be «common sense» for the typical user of `.fasta` files (which I'm not), not necessarily an error in OpenBabel.  It can't be all day Fortran (for its typical leading safeguard instruction `implicit none`) ...

[2021-04-27.zip](https://github.com/openbabel/openbabel/files/6383115/2021-04-27.zip)

**Comment by fredrikw** [comment]
To clear up the issue, do you still have a problem and use case for converting SMILES to Fasta @shahik? I still think that going that way is not something that we could expect OpenBabel to do so my suggestion is to close this issue.
On the other hand, Fasta to SMILES or any other "normal chemistry format" should work, without using -j in my opinion, but that is a different issue and it would be nice with example files from a real scenario. So if you have good examples there @shahik I would suggest creating a new issue.
