### ISSUE TITLE
fail to calculate logP using pybel

### ISSUE THREAD

**Issue by dalong12** [openbabel/openbabel#2372]
- [X] I believe this to be a bug with Open Babel

## Environment Information
Open Babel version: 3.1.1
Operating system and version: win10, python 3.8 anaconda

## Expected Behavior

mol smiles CC(N)C1=CC2=C(C=C1)C=NC=C2, logP from chemaxon 1.29

## Actual Behavior

I use pybel to calculate the logP of the mol above, the result is 0

## Steps to Reproduce

from openbabel import pybel as pb
my=pb.readstring("smi", "CC(N)C1=CC2=C(C=C1)C=NC=C2")
my.calcdesc(descnames=['MW', 'logP', 'HBA1', 'HBD'])
{'MW': 172.22637999999998, 'logP': 0.0, 'HBA1': 2.0, 'HBD': 1.0}

**Comment by fredrikw** [comment]
Some follow-ups:
* Running the following command in a conda-environment (Python 3.9) on Windows similarly give a logP of 0 and in addition prints out an error.
```
obabel -ismi -:"CC(N)C1=CC2=C(C=C1)C=NC=C2" -osmi --append logP
==============================
*** Open Babel Error  in OpenBabel::OBGroupContrib::ParseFile
   Could not find contribution data file.
CC(N)c1cc2c(cc1)cncc2   0
1 molecule converted
```
* On my regular install (conda environment in wsl2-ubuntu) I get logP 2.95.

So it seems like the problem is the GroupContrib file on the windows-conda.

**Comment by fredrikw** [comment]
For me, setting BABEL_DATADIR as in 
`set BABEL_DATADIR=MY\PATH\TO\Miniconda3\share\openbabel` before running the commands fixed the problem. So there is a problem with that setting on conda/windows.

**Comment by dalong12** [comment]
> For me, setting BABEL_DATADIR as in
> `set BABEL_DATADIR=MY\PATH\TO\Miniconda3\share\openbabel` before running the commands fixed the problem. So there is a problem with that setting on conda/windows.

Thank you, fredrikw. I repreated and got your result. But I did not success when I add environment in python.
![image](https://user-images.githubusercontent.com/72644114/120741407-963e6500-c527-11eb-87d3-b9a5b21101b0.png)

**Comment by dalong12** [comment]
Thank you. fredrikw. problem solved.

**Comment by fredrikw** [comment]
Just a follow-up. This issue is taken care of by https://github.com/conda-forge/openbabel-feedstock/pull/22.

If you run `conda update -c conda-forge openbabel` and make sure you get a version of `3.1.1-py39hfc62d72_2` or later the BABEL_DATADIR is set automatically on activation of the conda environment.
