### ISSUE TITLE
Wrong bond order on converting radical species from SMILES to XYZ using gen3d

### ISSUE THREAD

**Issue by veerupaksh** [openbabel/openbabel#2391]
- [ ] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
- Open Babel version: 3.1.1
- Operating system and version: CentOS Linux 7 (Kernel: Linux 3.10.0-1062.9.1.el7.x86_64)

##
I am trying to convert "[CH2][CH2].[CH2]CCC" and "[CH2][CH]C.[CH2]CC" to xyz files using the gen3d option.

## Expected Behaviour
There should be no double bond formation in the "[CH2][CH2]" and "[CH2][CH]C" molecules on conversion to xyz.

## Actual Behavior
On conversion to xyz, a double bond is introduced in the molecules and the strings become "C=C.[CH2]CCC", and "C=CC.[CH2]CC".

## Steps to Reproduce
I have tried converting the SMILES to xyz directly, as well first to formats that explicitly store bond orders like cml, sdf, mol, and then to xyz but the problem persists.

## 
Has anyone else faced the same problem and found a solution? Any suggestions for a workaround will be highly appreciated.

Thanks,
Veerupaksh

**Comment by fredrikw** [comment]
xyz files don't have any bond information in them so there is no double bond introduced by the conversion to xyz. When converting back to SMILES, the double bonds are introduced when trying to guess the bond order from the atom positions. So if you are interested in bond information, I would suggest a different file format.

**Comment by nbehrnd** [comment]
@veerupaksh It is not evident how you engaged the SMILES strings because `C=C.[CH2]CCC` is again SMILES notation.  But if your input on the CLI / terminal / `cmd.exe` either is

`obabel -:'[CH2][CH2].[CH2]CCC' --gen3d -oxyz`
or
`obabel -:"[CH2][CH2].[CH2]CCC" --gen3d -oxyz`

to report a 3D geometry of the two molecules (concatenation by full stop / period  `.`), the result is going to be similar (not identical, see e.g., the documentation [here](https://open-babel.readthedocs.io/en/latest/3DStructureGen/SingleConformer.html?highlight=gen3d#gen3d)) to the one below:
```
19

C          2.55723        1.72326       -1.82618
H          2.17075        2.56659       -1.26620
H          1.94828        1.26022       -2.59356
C          3.86186        1.21418       -1.54383
H          4.46746        1.67218       -0.77086
H          4.24458        0.36522       -2.09776
C          0.17202       -0.92830        1.42068
H         -0.13346       -1.03491        2.45554
H         -0.59236       -0.73610        0.67606
C          1.60773       -0.72665        1.06817
C          2.53582       -1.54800        1.96102
C          3.99505       -1.33776        1.58761
H          1.84536        0.33900        1.15880
H          1.75601       -1.01012        0.02008
H          2.29334       -2.61428        1.87570
H          2.39208       -1.26890        3.01199
H          4.18309       -1.64155        0.55289
H          4.64240       -1.93295        2.23926
H          4.27981       -0.28619        1.69482
1 molecule converted
```
(The result may be directed into a permanent record, e.g. by `obabel -:'[CH2][CH2].[CH2]CCC' --gen3d -oxyz -O output.xyz`.)

**Comment by veerupaksh** [comment]
Thank you @fredrikw, @nbehrnd for the suggestions. Performing an energy minimization on the generated 3d coordinates solved the issue by creating updated coordinates.
