### ISSUE TITLE
Inconsistent atom typing for linux and windows

### ISSUE THREAD

**Issue by schallerdavid** [openbabel/openbabel#2409]
Dear OpenBabel-Team,

it would be great if you could take a look at the following inconsistency:

- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 
 - 3.1.1 (Python 3.9, conda-forge)
 
Operating system and version: 
 - Ubuntu 20.04
 - Windows 10

## Expected Behavior
Consistent atom typing across different operating systems.

## Actual Behavior
Atom type differs for atom 2373 from ligand 03P in PDB entry 3POZ:

Linux -> Nar
Windows 10 -> N2

## Steps to Reproduce
- download 3POZ from the [PDB](https://www.rcsb.org/structure/3POZ)
- run the following code on ubuntu and windows:

```
from openbabel import pybel

molecule = list(pybel.readfile("pdb", "/path/to/3poz.pdb"))[0]

for atom in molecule.atoms:
    if atom.index == 2373:
        print(atom.type)
```

**Comment by fredrikw** [comment]
Hello,

When you run the code on windows you get warnings that you cannot open the file space-groups.txt
This is due to conda openbabel not being able to find the datafile folder properly on Windows. The easiest workaround is to set it manually via set BABEL_DATADIR=\path\to\condaenv\share\openbabel before running the code, or set the corresponding environment variable in another way.

But it should be fixed in the conda-package in the end...

**Comment by schallerdavid** [comment]
@fredrikw , thanks for spotting this. Applying this workaround leads to correct atom typing on windows.

**Comment by fredrikw** [comment]
Just a follow-up. This issue is taken care of by https://github.com/conda-forge/openbabel-feedstock/pull/22.

If you run `conda update -c conda-forge openbabel` and make sure you get a version of `3.1.1-py39hfc62d72_2` or later the BABEL_DATADIR is set automatically on activation of the conda environment.

**Comment by schallerdavid** [comment]
Thanks, I'll give it a try soon.

**Comment by schallerdavid** [comment]
Fixed, thanks for your help!
