### ISSUE TITLE
no H when converting cdxml to SMILES or others

### ISSUE THREAD

**Issue by RicardoMBorges** [openbabel/openbabel#2416]
Hello,
I'm trying to get SMILES from cdxml but I always get no H in the output. Is there a clever way to solve this?

Thanks

**Comment by nbehrnd** [comment]
@RicardoMBorges In similar tune like @fredrikw , capitalization (or absence of such) may *implicitly* carry the number of of hydrogens present.  E.g., `C1CCCCC1` to represent cyclohexane, `c1ccccc1` to represent benzene (lower case c, n, o, s represent aromatic systems).  You may add the reasoning why you need explicit hydrogens in the SMILES string, or/and an example file where you think it would be useful.  Because a benzene .cdxml generated from ChemDraw's [test page](https://chemdrawdirect.perkinelmer.cloud/js/sample/index.html#) isn't necessarily rewritten by 

```bash
obabel -icdxml benzene.cdxml -osmi
```
into `c1ccccc1`  (example file attached in the .zip archive).

[benzene.cdxml.zip](https://github.com/openbabel/openbabel/files/7328283/benzene.cdxml.zip)

**Comment by nbehrnd** [comment]
@fredrikw Based on your comment, I run

```bash
obabel -:'c1ccncc1' -osmi -h
obabel -:'c1ccncc1' -osmi -xh
obabel -:'c1ccncc1' -ocan -h
obabel -:'c1ccncc1' -ocan -xh
```
with OpenBabel 3.1.1. as provided by Linux Debian 12/bookworm, branch testing.  None of them added explicit hydrogens around the pyridine, nor a form like `C1=CN=CC=C1` e.g. said ChemDraw JS suggests as a plausible solution.  Since ```obabel -:'c1ccncc1' -oxyz -h``` did add them (and ```obabel -:'c1ccncc1' -oxyz -xh``` did not), I probably misunderstand the manual (section 18.1.7). Or do I?

**Comment by fredrikw** [comment]
Could you give an example? Both the initial cdxml, the SMILES produced, and the final cdxml.

**Comment by RicardoMBorges** [comment]
Do you use ChemDraw to generate the initial .cdxml, .or. do you use an other program (e.g., Marvin, or JChem [for Excel]) to generate a .cdxml in first place? If so, which version?
>> YES. ChemDraw version 20.1.1.125
