### ISSUE TITLE
GROMOS96 format (gr96) units conversion (nanometers)

### ISSUE THREAD

**Issue by kkempfer** [openbabel/openbabel#2471]
Dear all,

- [X] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: Open Babel 3.1.0 -- Feb 23 2022 -- 12:25:14
Operating system and version: Windows Subsystem for Linux (WSL 2), Ubuntu 20.04 LTS

## Expected Behavior
When converting a file to [GROMOS96](https://open-babel.readthedocs.io/en/latest/FileFormats/GROMOS96_format.html) (gr96) using the `-n` option in `obabel` command line program, I expect the output to be written in nanometers.

## Actual Behavior
Units are not converted.

## Steps to Reproduce
```
$ obabel -:"C" -O methane.xyz --title methane --gen3d best
1 molecule converted
$ obabel methane.xyz -o gr96
#GENERATED BY OPEN BABEL 3.1.0
TITLE
methane
END
POSITION
    1   UNL    C       1         0.93899        -0.05140         0.06030
    1   UNL    H       2         2.03119        -0.05140         0.06030
    1   UNL    H       3         0.57493        -0.85612        -0.58218
    1   UNL    H       4         0.57493         0.90736        -0.31537
    1   UNL    H       5         0.57492        -0.20545         1.07845
END
1 molecule converted
$ obabel methane.xyz -o gr96 -n
#GENERATED BY OPEN BABEL 3.1.0
TITLE
methane
END
POSITION
    1   UNL    C       1         0.93899        -0.05140         0.06030
    1   UNL    H       2         2.03119        -0.05140         0.06030
    1   UNL    H       3         0.57493        -0.85612        -0.58218
    1   UNL    H       4         0.57493         0.90736        -0.31537
    1   UNL    H       5         0.57492        -0.20545         1.07845
END
1 molecule converted
```

Note that coordinates in the [GRO](https://open-babel.readthedocs.io/en/latest/FileFormats/GRO_format.html) file format are indeed written in nanometers.
```
$ obabel methane.xyz -o gro
methane
5
    1UNL      C    1   0.094  -0.005   0.006
    1UNL      H    2   0.203  -0.005   0.006
    1UNL      H    3   0.057  -0.086  -0.058
    1UNL      H    4   0.057   0.091  -0.032
    1UNL      H    5   0.057  -0.021   0.108
   0.00000   0.00000   0.00000
1 molecule converted
```

**Comment by nbehrnd** [comment]
Do not call `-n`, but `-xn` (mnemonics _use_ or _execute_ a format specific option which `-n` is).  As an illustration (obabel 3.1.1 as provided in Linux Debian 12/bookworm (branch testing):

```bash
$ obabel -:"C" --title "methane (Angstroms, default)" -h --gen3d -o gr96
#GENERATED BY OPEN BABEL 3.1.1
TITLE
methane (Angstroms, default)
END
POSITION
    1   UNL    C       1         0.95144         0.06266        -0.06096
    1   UNL    H       2         2.04364         0.06266        -0.06096
    1   UNL    H       3         0.58738         0.24046        -1.07523
    1   UNL    H       4         0.58737         0.85214         0.60016
    1   UNL    H       5         0.58737        -0.90463         0.29219
END
1 molecule converted
```
but
```bash 
$ obabel -:"C" --title "methane (nanometers)" -h --gen3d -o gr96 -xn
#GENERATED BY OPEN BABEL 3.1.1
TITLE
methane (nanometers)
END
POSITION
    1   UNL    C       1         0.10736        -0.00092         0.00671
    1   UNL    H       2         0.21658        -0.00092         0.00671
    1   UNL    H       3         0.07095         0.07563        -0.06216
    1   UNL    H       4         0.07095         0.02045         0.10744
    1   UNL    H       5         0.07095        -0.09884        -0.02515
END
1 molecule converted
```
---

Given the simplicity of methane, GROMOS possibly is just fine with default `--gen3d` as starting geometry OpenBabel provides here.  It often is the sweet spot of computational cost among the five levels of 3D coordinate generation offered. (The manual points to a dedicated publication to balance pros and cons.) For methane in particular, there is no need for an extended permutation of rotor search `--gen3d best` (or `--gen3d slowest`) offer, either. 

Because you mention GROMOS, _I speculate_ you aim to provide multiple _conformers_ of one (more complex) molecule for GROMOS to start with.  OpenBabel can provide you these geometries as individual, separate models, too.
