### ISSUE TITLE
Index mismatch in OBRing*->_path

### ISSUE THREAD

**Issue by Mblakey** [openbabel/openbabel#2478]
- [x] I believe this to be a bug with Open Babel
- [ ] This is a feature request

## Environment Information
Open Babel version: 3.1.1_1
Operating system and version: macOS Monterey: 12.2.1

## Expected Behavior
Documentation lists _path as "the path of this ring (i.e., the atom indexes)", however these will not match up to atom indexes created from atom->GetIndex()

0,1,2,3,4,5
or 
2,3,4,5,0,1

## Actual Behavior

3, 4, 5, 6, 1, 2

Using the FOR_ATOMS_OF_MOL iterator yields: 0,1,2,3,4,5

## Steps to Reproduce

```
    const char* smiles = "c1cccc1"
    OpenBabel::OBMol *Mol = new OpenBabel::OBMol;
    OpenBabel::OBConversion conv;
    conv.SetInFormat("smi");
    conv.ReadString(Mol, smiles);
    Mol->DeleteHydrogens();

    FOR_RINGS_OF_MOL(ring, Mol){
        unsigned int ring_size = ring->Size();
        bool aromatic = ring->IsAromatic();
        std::vector<int> ring_indexes = ring->_path;
        for (auto v: ring_indexes){
            std::cout << v << " ";
        }
        std::cout << "\n";
    }

    delete Mol;
```

**Comment by fredrikw** [comment]
Hi,

I think that you may have (understandably) confused GetIdx() with GetIndex() where the first returns 1-based atom indexes and the latter returns 0-based atom indexes.
Due to legacy reasons (IIRC), OpenBabel uses 1-based indexing but provides the GetIndex method to get 0-based indexes. So it is completely expected to get 1-based indexing of the ring.
