### ISSUE TITLE
AssignAromaticFlags example

### ISSUE THREAD

**Issue by MJoseom** [openbabel/openbabel#2508]
Hello, 

I would like to apply in my python script the next function of openbabel to determine the aromaticity: "Applying a model involves creating an instance of OBAromaticTyper(), and calling AssignAromaticFlags() passing an OBMol as a parameter."

However, after trying to find a clear example, it has been impossible to understand why the output is empty. Here, I copy a simple code that I am using:

> #### Reading the molecule
> mol = pybel.readstring("smi", "CCC(C1)CCC2[n+]1CCC3C2[nH]C4C3CCCC4")
> #### Checking the aromaticity
> [int(atom.IsAromatic()) for atom in openbabel.OBMolAtomIter(mol.OBMol)]
> #### Adding the aromatic flags
> molmod = openbabel.OBAromaticTyper().AssignAromaticFlags(mol.OBMol)

molmod is an empty object while I expected the molecule with aromatic flags. 
What I am doing wrong? 

Thank you so much for your help and time!!

**Comment by nbehrnd** [comment]
The SMILES string presented by you is not about aromatic structure.

+ The implicit form to describe aromatic compounds is to use lower-case symbols of the non-H atoms.  Thus, for example instead of `C1CCNCC1` (piperidine, saturated and non-aromatic) to write `c1ccncc1` (pyridine, non-saturated and aromatic). The more frequently seen cases apply this pattern on C, N, O, P, and S.  

+ There is a more explicit form, where -- like in Kekulé formulae -- you see an alternating pattern of single and double bonds.  (This is a formalism only, because aromatic bonds are neither single, nor double bonds.)  Thus, instead of `c1ccccc1` to describe benzene, you may write `C1=CC=CC=C1`, too.

The potential hurdle on the side of chemistry is that by e.g., cyclopentadiene (`C1C=CC=C1`), insaturation _alone_ is a necessary, yet not a sufficient condition to consider a compound as _aromatic_.  On the other side, there are multiple SMILES dialects used; OpenBabel provides canonical, universal, and inchified SMILES ([reference](https://open-babel.readthedocs.io/en/latest/FileFormats/SMILES_format.html)).  The more complex the molecular structure to describe, the higher the chance you are going to spot a difference in SMILES strings assigned along these rules.  Assuming you didn't know about SMILES earlier, there is a brief entry in [wikipedia](https://en.wikipedia.org/wiki/Simplified_molecular-input_line-entry_system), and thanks to Daylight some [tutorial](https://daylight.com/dayhtml_tutorials/languages/smiles/index.html), [theory](https://daylight.com/dayhtml/doc/theory/theory.smiles.html), and [examples](https://www.daylight.com/dayhtml_tutorials/languages/smiles/smiles_examples.html) compiled in one spot to get started.

In case you launch your scripts from the CLI, a slight modification of your code offers to test one SMILES string at a time:

```python
#!/usr/bin/env python3

import argparse

from openbabel import openbabel
from openbabel import pybel


def main():
    """Collect SMILES and perform the analysis"""
    parser = argparse.ArgumentParser(
        description='Check if OpenBabel considers a structure aromatic')
    parser.add_argument('smiles', help='structure to test (SMILES string)')
    args = parser.parse_args()

    # Reading the molecule
    mol = pybel.readstring("smi", args.smiles)

    # Checking the aromaticity
    print([
        int(atom.IsAromatic()) for atom in openbabel.OBMolAtomIter(mol.OBMol)
    ])


if __name__ == '__main__':
    main()
```

**Comment by MJoseom** [comment]
Thank you so much for your nice explanation @nbehrnd. 

Actually, I admit that I modified on purpose the SMILE to be sure that the aromatic flag was not well determined. Just to simplify, I have a list of molecules in  MOL2 file that have been dearomatized with another software and openbabel didn't recognize the aromaticity by atoms (example attached, just change the extension). [test.txt](https://github.com/openbabel/openbabel/files/9055935/test.txt)

Because of that, I want to know how to use "AssignAromaticFlags" function. 

Nevertheless, you give me the idea to transform the molecule first to new smile and re-read it, like that it is working! However, not sure if the main problem with the MOL2 corresponds to the both ways to present the aromaticity (Kekule or lower-case) or it is a bug.

 `mol = next(pybel.readfile("mol2", "./test.mol2"))`

 `[int(atom.IsAromatic()) for atom in openbabel.OBMolAtomIter(mol.OBMol)]`

> [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

 `mol.write("can")`

> `O=C(N[C@@H](C(=O)N[C@H](CNC1=CC=C(C=C1)N1CCCCC1)CCC1=CC=CC=C1)CC1=CC=CC=C1)OCC1=CC=CC=C1\tBDB50137400\n`

 `mol = pybel.readstring("can", "O=C(N[C@@H](C(=O)N[C@H]CNC1=CC=C(C=C1)N1CCCCC1)CCC1=CC=CC=C1)CC1=CC=CC=C1)OCC1=CC=CC=C1")`

  `mol.OBMol.AddHydrogens()`

> True

 `[int(atom.IsAromatic()) for atom in openbabel.OBMolAtomIter(mol.OBMol)]`

> [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

**Comment by fredrikw** [comment]
Without knowing the full specifications of the MOL2 file format it looks like OpenBabel is accepting the aromaticity specified in the infile and hence set the "AromaticityPerceived" flag to true which in turn will make IsAromatic to just report the values from the file.
The SMILES reader doesn't "trust" the incoming aromaticity designation since different toolkits have different aromaticity models so when you bounce through SMILES, OpenBabel unsets the "AromaticityPerceived" which is why IsAromatic finds the aromatic atoms.
So the simplest solution for you is to unset the flag before calling IsAromatic. (I also change the iteration to use pybel's mol.atoms to show a different way of iterate over atoms...)
```python
>>> [int(atom.OBAtom.IsAromatic()) for atom in mol.atoms]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>> mol.OBMol.SetAromaticPerceived(False)
>>> [int(atom.OBAtom.IsAromatic()) for atom in mol.atoms]
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

**Comment by nbehrnd** [comment]
@MJoseom Just changing the bond order (fourth column in the bond block

```
@<TRIPOS>BOND
1	1	2	2
2	2	3	1
3	3	4	1
4	4	5	1
5	5	6	1
```
) will not suffice to perform the saturation.  It is, as indicated by you, a bit more complicated than the substitution of strings (e.g., by AWK) because a) some files describe the aromatic rings by alternating single and double bonds marked by `1` and `2` respectively, while b) `2` _possibly_ should be retained to describe e.g., C=O of esters and amides.

Noteworthy, «just» rewrite the .mol2 as provided by you with 

```bash
obabel -imol2 test.txt -O rewrite_01.mol2
```
yields a bond block where the amides explicitly marked _as such_ (by string `am`).  On the other hand, passing the .xyz format lacking any information of bond order, OpenBabel assigns the bonds of the aromatic rings with an explicit `ar`, too:

```bash
obabel -imol2 test.txt -oxyz | obabel -ixyz -O rewrite_02.mol2
```
By change of the bond order e.g., of a former phenyl ring, both additional hydrogen atoms (and their coordinates) as well a new coordinates of the carbon atoms need to be updated (new bond lengths C-C).  If one wouldn't need to reuse the coordinates of the atoms not affected by the saturation, the «saturation of the SMILES string» might be an alternative to handling `.mol2`.  Because once I wrote such a script ([link](https://github.com/nbehrnd/datawarrior_saturate_Murcko_scaffolds), though currently constrained to at most one stereogenic center), may you indicate the program you use to perform the saturation?

**Comment by Dadiao-shuai** [comment]
I have a little question, Is all kinds of `aromatic carbon` atom be marked as `CA`?

ATOM      1  N   MOL A   1       4.841  27.576   5.310  1.00  0.00           N1+
ATOM      2  CA  MOL A   1       5.733  26.394   5.165  1.00  0.00           C  
ATOM      3  C   MOL A   1       7.174  26.772   5.504  1.00  0.00           C  
ATOM      4  O   MOL A   1       7.624  27.887   5.218  1.00  0.00           O  
ATOM      5  CB  MOL A   1       5.638  25.818   3.750  1.00  0.00           C  
ATOM      6  CG  MOL A   1       5.827  26.846   2.652  1.00  0.00           C  
ATOM      7  CD  MOL A   1       5.625  26.275   1.262  1.00  0.00           C  
ATOM      8  OE1 MOL A   1       4.663  25.497   1.065  1.00  0.00           O1-
ATOM      9  OE2 MOL A   1       6.425  26.620   0.363  1.00  0.00           O  
ATOM     10  N   MOL A   1       7.873  25.856   6.163  1.00  0.00           N  
ATOM     11  CA  MOL A   1       9.258  26.072   6.560  1.00  0.00           C  
ATOM     12  C   MOL A   1      10.101  24.918   6.047  1.00  0.00           C  
ATOM     13  O   MOL A   1      10.182  23.864   6.682  1.00  0.00           O  
ATOM     14  CB  MOL A   1       9.346  26.196   8.079  1.00  0.00           C  
ATOM     15  CG  MOL A   1       8.649  27.441   8.588  1.00  0.00           C  
ATOM     16  OD1 MOL A   1       9.270  28.518   8.521  1.00  0.00           O1-
ATOM     17  OD2 MOL A   1       7.474  27.357   9.012  1.00  0.00           O  
ATOM     18  N   MOL A   1      10.686  25.115   4.869  1.00  0.00           N  
ATOM     19  CA  MOL A   1      11.498  24.093   4.226  1.00  0.00           C  
ATOM     20  C   MOL A   1      12.984  24.399   4.268  1.00  0.00           C  
ATOM     21  O   MOL A   1      13.784  23.442   4.192  1.00  0.00           O1-
ATOM     22  CB  MOL A   1      11.038  23.922   2.785  1.00  0.00           C  
ATOM     23  CG  MOL A   1       9.583  23.466   2.770  1.00  0.00           C  
ATOM     24  CD1 MOL A   1       8.819  24.197   1.708  1.00  0.00           C  
ATOM     25  CD2 MOL A   1       9.521  21.955   2.602  1.00  0.00           C  
ATOM     26  OXT MOL A   1      13.334  25.592   4.378  1.00  0.00           O

**Comment by rwxayheee** [comment]
Hi @Dadiao-shuai 
No, in your file CA is the name of the atom not the atom type. More likely, it means alpha carbon as atom name. See below for an explanation of the coordinate section in PDB files: 
https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html

**Comment by Dadiao-shuai** [comment]
HI @rwxayheee , my pdb file is a ligand, so `CA` is not an alpha carbon of a residue.
BTW, I've updated my question: I have a little question, Is all kinds of aromatic carbon atom in a LIG.pdb be marked as `CA,CD...`?

**Comment by rwxayheee** [comment]
@Dadiao-shuai 
` my pdb file is a ligand, so CA is not an alpha carbon of a residue.`
It actually is an alpha carbon of a residue. Your ligand is a polypeptide. 

No CA,CD are atom names. They can be arbitrary. But if they are standard atom names in amino acids, they mean alpha carbon, delta cabon.
