### ISSUE TITLE
SMILES -> OXYZ coordinate generation --gen3D not correctly identifying forcefield

### ISSUE THREAD

**Issue by raulorteg** [openbabel/openbabel#2585]
## Environment Information
**Open Babel version:** Open Babel 3.1.1 -- Feb  7 2022 -- 06:51:49
**Operating system and version:** Ubuntu 22.04.2 LTS

## Expected Behavior
3D-structure generation from given SMILES string. Converting from SMILES -> OXYZ (coordinates).
By using the defaults in the `--gen3D` it should generate valid OXYZ coordinates (not broken fragments)

## Actual Behavior
Instead it generates OXYZ coordinates that when visualized correspond to a molecule broken in fragments, with no warnings.

## Steps to Reproduce

Using as example the SMILES: "C1=Cc2csc(C3=c4[se]c5c(ccc6ncccc65)c4=CC3)c2[SiH2]1" if I try to generate the 3D structure (OXYZ):

1. Using the default parameters:
`obabel -:"C1=Cc2csc(C3=c4[se]c5c(ccc6ncccc65)c4=CC3)c2[SiH2]1" --gen3D -h -O test1.xyz`
(terminal output): $ 1 molecule converted
then I visualize the structure loading the XYZ coordinates with AVOGADRO:

![image](https://user-images.githubusercontent.com/69815654/231754101-807d8f4d-ddd7-4d72-9a31-d5d44d3ca14d.png)

2. Specifying the correct force-field to be used:
`obabel -:"C1=Cc2csc(C3=c4[se]c5c(ccc6ncccc65)c4=CC3)c2[SiH2]1" --gen3D -h --minimize --ff UFF -O test2.xyz`
(terminal output): $ 1 molecule converted
then I visualize the structure loading the XYZ coordinates with AVOGADRO:
![image](https://user-images.githubusercontent.com/69815654/231755213-bad4613c-8a08-427b-87a7-469f704e5fff.png)

From the openbabel `--gen3D` documentation (https://open-babel.readthedocs.io/en/latest/3DStructureGen/SingleConformer.html):
![image](https://user-images.githubusercontent.com/69815654/231755668-f732e09c-9869-43e6-a809-7c84c8f00c09.png)
`--gen3D`  will use MMFF94 by default which will not work since atoms like "Se" are not defined in MMFF94 (see https://open-babel.readthedocs.io/en/latest/Forcefields/mmff94.html#mmff94-force-field)
![image](https://user-images.githubusercontent.com/69815654/231756361-7dc07e2a-9822-4c84-bf93-5dbd7b7f7595.png)c

MMFF94 will not work because of some of the atoms (Se) present in my molecule, but that in principle its ok because according to the `--gen3D` documentation (https://open-babel.readthedocs.io/en/latest/3DStructureGen/SingleConformer.html) by default also it uses the `--medium` which DOES forcefield optimization.

## Summary
I believe that the default configuration of the `--gen3D` command should result in it recognizing that it cant use MMFF94 forcefield on my molecule because of the "Se" atom and then because by default it uses `--medium` it should optimize the forcefield and use UFF instead. And if this is not the case, and it is using MMFF94 it should print out a warning or do not give any output, since any other output would be wrong.

**Comment by ghutchis** [comment]
It does not use MMFF94 because of the selenium and silicon. The difference between the invocations is that you're doing more "cleanup" in the 2nd choice (by optimizing again UFF after the gen3d step).

Since you're saving to XYZ format, Avogadro has to re-perceive the bonds .. and in this case, since there isn't a ring fragment with the selenium, it's pretty weird.

`obabel -:'C1=Cc2csc(C3=c4[se]c5c(ccc6ncccc65)c4=CC3)c2[SiH2]1' -O gen3d.sdf --gen3d`

<img width="465" alt="Screenshot 2023-04-13 at 10 18 35 AM" src="https://user-images.githubusercontent.com/41128/231788665-44c192c8-40be-4b87-bfcb-abee45f0017a.png">

If instead, I add "best" to the `--gen3d` it's much cleaner:

`obabel -:'C1=Cc2csc(C3=c4[se]c5c(ccc6ncccc65)c4=CC3)c2[SiH2]1' -O best.sdf --gen3d best`

<img width="525" alt="Screenshot 2023-04-13 at 10 18 53 AM" src="https://user-images.githubusercontent.com/41128/231788909-2052a4b5-6abf-45ea-b66e-3bfba45aa773.png">

In principal, the `gen3d` would be better if there were some selenium fragments or fallback to the thiophenes, but for your purposes, it's probably easier to just supply `--gen3d best` which will also do some conformer searching.

**Comment by nbehrnd** [comment]
> The difference between the invocations is that you're doing more "cleanup" in the 2nd choice (by optimizing again UFF after the gen3d step).

In addition, openbabel reports if the task was achieved, and informs you if the selected force field is not suitable for the task ahead.  Compare the successful interaction with UFF

``` shell
$ obabel -:"C1=Cc2csc(C3=c4[se]c5c(ccc6ncccc65)c4=CC3)c2[SiH2]1" --gen3D -h --minimize --ff UFF -O test2.xyz
1 molecule converted
```

with one calling MMFF94, or MMFF94s

``` shell
$ obabel -:"C1=Cc2csc(C3=c4[se]c5c(ccc6ncccc65)c4=CC3)c2[SiH2]1" --gen3D -h --minimize --ff MMFF94 -O test2.xyz
Could not setup force field.
0 molecules converted
$ obabel -:"C1=Cc2csc(C3=c4[se]c5c(ccc6ncccc65)c4=CC3)c2[SiH2]1" --gen3D -h --minimize --ff MMFF94s -O test2.xyz
Could not setup force field.
0 molecules converted
```

**Comment by nbehrnd** [comment]
@raulorteg The current documentation about openbabel is [here](https://open-babel.readthedocs.io/en/latest/index.html) (including download as html, pdf, or epub for off-line access).

In section [Generating conformers for structures](https://open-babel.readthedocs.io/en/latest/Command-line_tools/babel.html?highlight=Generating%20conformers%20for%20structures#generating-conformers-for-structures), it however is MMFF94 which is stated as the default.

**Comment by raulorteg** [comment]
ok, Thanks a lot for the help!
