### ISSUE TITLE
Some source code packages could not find Python3 library during installation

### ISSUE THREAD

**Issue by HoaSoup** [openbabel/openbabel#2599]
Hello, thank you for your hard work in developing OpenBabel.

I found that all the compressed files labeled as "Source code" in [OpenBabel 3.1.1 latest release page](https://github.com/openbabel/openbabel/releases/tag/openbabel-3-1-1) could not find Python3 library when cmake is preparing for compilation on Ubuntu 22.04.
The compressed file "openbabel-3.1.1-source.tar.bz2" is not affected.

## Environment Information
Open Babel version: 3.1.1
Operating system and version: Ubuntu 22.04
Python version: 3.10.6. Packages python3-dev and libpython3-dev have been installed.

## Expected Behavior
During installation, "cmake .. -DPYTHON_BINDINGS=ON" should produce something like:
`-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found version "3.10.6")`
And thus, Python bindings should be able to be compiled.

## Actual Behavior
cmake produced no line indicating PythonLibs has been found. Hence this warning:
`-- Warning: Python bindings NOT found. Generate using -DRUN_SWIG=ON.`

I am quite new to OpenBabel and computer so I am not sure if I am missing any points regarding the difference and the intended usage of these compressed files.

Best regards,
HoaSoup

**Comment by robertwerner67** [comment]
Maybe your current interest is the conversion e.g., of .sdf into .xyz from the CLI (or, thanks to obgui, a GUI) only.  (Because you mention you want to familiarize with the program first, a bookmark https://open-babel.readthedocs.io/en/latest/ can be helpful.) This contrasts to a later contribution to openbabel's source code (if you want).

If this assumption is correct, the installation of openbabel as package from Ubuntu's servers (`sudo apt install openbabel`) both suffices and resolves the dependencies for you.  An example of  a GUI of the package manager is synaptic.

**Comment by HoaSoup** [comment]
Thank you for your replies. I was worried that I could have missed something important during the compilation. Phew!

**Comment by HoaSoup** [comment]
Thank you for your replies. I was worried that I could have missed something important during the compilation. Phew!
