### ISSUE TITLE
Not generating the same torsion lists for conformers

### ISSUE THREAD

**Issue by pyrodancer123** [openbabel/openbabel#2644]
## Environment Information
Open Babel version: 3.1.0

## Expected Behavior
I have a selection of conformers of the same molecule. I want to collect all of the torsions in one file for comparison purposes. This should be easily done using the report file type.

## Actual Behavior
However, the list of torsions that are generated in this format vary from conformer to conformer, which makes it quite a bit more difficult. 

I have attached the reports for three of the conformers for a small molecule to illustrate that the torsion list is different.
[CCB-CH2CN_1.txt](https://github.com/openbabel/openbabel/files/13367470/CCB-CH2CN_1.txt)
[CCB-CH2CN_2.txt](https://github.com/openbabel/openbabel/files/13367471/CCB-CH2CN_2.txt)
[CCB-CH2CN_3.txt](https://github.com/openbabel/openbabel/files/13367472/CCB-CH2CN_3.txt)

## Steps to Reproduce

I am simply using the basic convert feature to convert Gaussian job log files to report files. Input log files are attached below.
[CCB-CH2CN_1.log](https://github.com/openbabel/openbabel/files/13367504/CCB-CH2CN_1.log)
[CCB-CH2CN_2.log](https://github.com/openbabel/openbabel/files/13367505/CCB-CH2CN_2.log)
[CCB-CH2CN_3.log](https://github.com/openbabel/openbabel/files/13367506/CCB-CH2CN_3.log)

**Comment by nbehrnd** [comment]
What do you want to do *after* the sort?  Try this:

- option A) is an edit in place, in the file.  You need a good text editor.  In Emacs, jump the block of interest (`C-s`, followed by the criterion e.g. `BOND ANGLES`), mark the block by `M-h` and run `M-x sort-lines`.  After that, you however have to put back `BOND ANGLES` to lead this block because an explicit empty space (here leading a column) has a higher priority in this sort, than `B` of string `BOND ANGLES`.
  
  If you prefer vim, jump to the block by `/BOND ANGLES/`.  Advance one additional line (`j`) to the first line of the array.  Enter the visual mode (`v`), mark all to the end of this block (`}`) and run the command `:sort`.  In case you didn't advance the single line before entering the visual mode and marked the whole paragraph (including the line `BOND ANGLES`), you now have to copy and yank this line up to the beginning of this block -- similar to Emacs.
  There equally is `gvim` (vim with some GUI added); here you can mark the region of interest with your mouse before running the command `:sort`.

- option B), your interest is only this very block in an eventually separate file.  After  manual extraction of the region of interest, perform a natural sort.  In Linux, you can run  `sort -n input.txt` with a result you can redirect into a new file.   (The natural sort puts the string `BOND ANGLES` ahead of the array.)

  In Linux, csplit allows you to skip the manual search and copy prior to the sort, too.  A minimal working example is

  ```shell
  csplit CCB-CH2CN_1.txt '/^BOND ANGLES$/' -s '/^$/' -f out
  ```

  to indicate the file to process, the pattern at the start of the paragraph of interest separated from the next one by an empty line (hence `-s '/^$/'`).  And to store the output  into files `out`.  It then is file `out01` which is about the block `BOND ANGLES` you can submit to the sort.

**Comment by pyrodancer123** [comment]
It's not the pulling of the block that is the problem. It's that the physical lists don't have the same entries. If you compare the output report files for conformer 2 and conformer 3, the lists of torsions are completely different.

My sorting isn't the issue. The facts that the lists don't match is.

**Comment by pyrodancer123** [comment]
Yes, that is exactly the issue. How am I supposed to sort and compare torsions if the pathing is stochastic and not systematic? Surely, it should start at atom 1 and proceed logically to 2, then 3, and so forth? 

I'm coding in Linux, as I have no experience coding in Python, and having to write a code to flip all those fields and compare would be a pain for something that shouldn't be a problem to begin with.

**Comment by fredrikw** [comment]
I think the torsion angle should be the same regardless of what direction you look at it so I would say the differences are from the different conformers.
