### ISSUE TITLE
Parse error on line 4 (ATOM) : Unknown or inappropriate tag

### ISSUE THREAD

**Issue by NooraAz** [openbabel/openbabel#2666]
## Environment Information
Open Babel version: OpenBabel/2.4.1-intel-2017b-Python-2.7.14
Operating system and version: linux

## Expected Behavior
I am trying to do flexible docking with Autodock vina. but I get this error while docking, it says line 4 of ligand file can not be parsed. this line is the first ATOM line. I saw people had suggested using -r tag, but I already use -xr in conversion to pdbqt. 

I have attached both pdb and pdbqt of my ligand.
[Archive.zip](https://github.com/openbabel/openbabel/files/13966651/Archive.zip)

**Comment by ghutchis** [comment]
You're reporting a bug in Open Babel 2.4?

Please confirm this is still a bug with Open Babel 3.1 first.

**Comment by rwxayheee** [comment]
Hi @NooraAz

The problem was caused by missing "ROOT" and "ENDROOT" which are structural keywords in ligand PDBQT files for Vina. 
`-r` converts the molecule to a rigid receptor PDBQT. Your ligand is indeed fully rigid without undergoing ring breaking, but it has to have "ROOT" and "ENDROOT" to represent the "tree structure" of a ligand. 

There are various options to prepare ligand PDBQT for Vina:
Obabel
`obabel -i pdb hexaA-result_106399.pdb -o pdbqt`
The residue names might change, but it's not harmful to the docking calculation. You can explore better ways of doing this within the version that's available to you, just don't use `-r`. 

Geometry-based Approach
**prepare_receptor** in https://ccsb.scripps.edu/adfr/documentation/
The residue names can be preserved. 

Valence-based Approach with Interface to RDKit
https://github.com/forlilab/Meeko?tab=readme-ov-file#1-make-pdbqt-files
See if you'd be interested to register your ligand as a RDKit molecule along with the ligand preparation

**Comment by NooraAz** [comment]
Thanks so much @rwxayheee . It solved my issue!

**Comment by dkoes** [comment]
Shameless plug here, but flexible docking is a lot easier with gnina (you can directly specify what residues you want to be flexible without having to setup separate files):
https://github.com/gnina/gnina?tab=readme-ov-file#usage

**Comment by NooraAz** [comment]
Thanks @dkoes . I just needed to follow the steps of another paper, that had worked with Vina, but I will try gnina as well.

**Comment by David-OConnor** [comment]
Does anyone have a fix for this if already not using the `-r` CLI flag? Babel 3.1 -> The latest Vina.

I downloaded and tried the `prepare_ligand`  program above, but it seems it (and its similar one for targets?) supports neither CIF, nor sdf files. 

edit: I think `-xr`, on the Target molecule, is the required flag.

**Comment by rwxayheee** [comment]
Hi @David-OConnor 

You can use our Python APIs in Meeko and basically import any parsers to parse any files. See here for a basic example: 

https://meeko.readthedocs.io/en/release-doc/lig_prep_advanced.html#from-python

See this for an alternate way of ligand preparation: 

https://github.com/forlilab/Meeko/issues/317#issuecomment-2664225008
