### ISSUE TITLE
Overlapping atoms after UFF optimisation

### ISSUE THREAD

**Issue by jennijones** [openbabel/openbabel#2687]
I have a SMILES string for a molecule which I want to generate 3D coordinates for and optimise with UFF. My code is: 

```
from openbabel import openbabel as ob
from openbabel import pybel as pb

smi = 'c1ccc(N2CCB3c4ccccc4N(c4ccccc4)c4ccc2cc43)cc1'

mol = pb.readstring('smiles', smi)

mol.addh()

mol.make3D()

ff = pb._forcefields["uff"]
        
success = ff.Setup(mol.OBMol)

if not success:
    ff = pb._forcefields["uff"]
    success = ff.Setup(mol.OBMol)
    if not success:
        sys.exit("Cannot set up forcefield")
        print(f'{mol_name}: Unable to set up forcefield')
        
ff.ConjugateGradients(100, 1.0e-3)
ff.FastRotorSearch(True) 
ff.WeightedRotorSearch(100, 25) 
ff.ConjugateGradients(250, 1.0e-4)
ff.GetCoordinates(mol.OBMol)

mol.write("xyz", f"{mol_name}_OB.xyz", overwrite=True)
```

The resulting xyz file has some very close/overlapping atoms so doesn't appear to be successfully optimised. If I try to optimise the geometry with the RDKit implementation of UFF, I get an error: 'Bad Conformer Id'. Is there a way to catch an unsuccessful UFF optimisations like this with Openbabel?

**Comment by nbehrnd** [comment]
Perspective chemistry: what is the origin of the SMILES string?  Because if read e.g., by [Marvin](https://marvinjs-demo.chemaxon.com/latest/demo.html), the hydrogen of carbon highlighted 

![marvin](https://github.com/openbabel/openbabel/assets/19709084/ef32b63c-5de3-46d6-9135-eaaa6a296ee1)

and the short bridge across boron, alkyl chain, nitrogen are not very comfortable in first place.  This appears to be very strained motif and in terms of energy, unusual expensive.

Perspective Python script: I were more comfortable if the force field to be used appears as  parameter of the geometry optimization, on the same line, e.g.

```
mol.make3D(forcefield="uff", steps=1000)
```

The underlying logic of your script seems to attempt an optimization with UFF if this available.  To me, this were better embedded in a try/except clause, i.e. a pattern in line of

```python
try:
    mol.make3D(forcefield="uff", steps=1000)
except Exception:
    print("launch of optimization failed")
```

Possibly there is a better exception condition than the very general `Exception` itself  (pylint will indicate it as a point to work on).  But at least the script will continue to work across this point, e.g. during an iteration over a list of SMILES even if the launch of the optimization in this step failed.

**Comment by jennijones** [comment]
Hi @nbehrnd thank you for your reply. This SMILES string came from the STONED algorithm (https://github.com/aspuru-guzik-group/stoned-selfies) which randomly generates new SMILES strings based on mutations to a starting string. Thank you for pointing out that the SMILES string has an unusual 2D structure as I didn't think to check this. 

I've implemented your try/except code for the optimisation instead. It still doesn't catch out a failed optimisation with this molecule, but I think this is a poor structure anyway as you pointed out. Is there a way to obtain the forces from the UFF optimisation, as I know this can be done with RDKit but I can't find a way to look at the forces with Openbabel?

**Comment by ghutchis** [comment]
At the moment, there isn't a great check for pathological cases with 3D generation. In this case, it's a very unusual motif, so the ring fragment library failed and the generator did the best it could.

Getting the gradients (above) is pretty easy.
