### ISSUE TITLE
Unexpected twisted double bond in output structure

### ISSUE THREAD

**Issue by arebruvold** [openbabel/openbabel#2699]
Unexpected cross of binding when generating chemical structures from smiles. I had difficulties opening exported .mol file using Compound Discoverer 3.3 SP3, which may or may not be related to this issue.

`obabel -:"N(=NF)F" -O "test.svg"`

or

`obabel -:"N(=NF)F" -O "Dinitrogen_difluoride.mol" --gen2D`

EDIT: This appears to also be the case in pubchems 2D viewer. Is this made using openbabel or am I missing something? See: https://pubchem.ncbi.nlm.nih.gov/compound/139594

## Environment Information
Open Babel version: 3.1.0
Operating system and version: Mac OS Sonoma 14.2 (23C64)

## Expected Behavior
F-N=N-F

## Actual Behavior
F-NXN-F or see attached image.
![test](https://github.com/openbabel/openbabel/assets/47218002/0e82373e-41ae-4125-84d0-3b114875a9a1)

**Comment by nbehrnd** [comment]
@arebruvold  No, it is not twisted.  However the configuration of the N=N double bond is not explicitly defined and a crossed double bond conventionally indicates you refer either i) to a mixture of (*E*) and (*Z*) difluorodiazene, or ii) you know there is the N=N double bond, but don't assign its configuration (perhaps by lack of information).  For writing a .mol/.mol2/.sdf file with atomic coordinates the situation is even worse than for an illustration: imagine you construct a physical model of this molecule and now don't know where to put the fluorine atoms.

In this particular case, you might better describe either the (*E*) configuration with `F\N=N\F`, or the (*Z*) isomer by `F\N=N/F`.  Don't forget CIP rules assign a non-bonding (here implicit) electron pair a priority `0`, i.e. even lower than for an atom of hydrogen.

Daylight compiled a set of references to learn more about (basic) SMILES' rules, see the [tutorial](https://www.daylight.com/dayhtml_tutorials/languages/smiles/index.html) and its links to theory and static examples.  Because SMILES and subsequently SMARTS can be very helpful to search in databases, I recommend to complement your study with the two blog posts by Noel O'Boyle [SMARTS for dummies](https://baoilleach.blogspot.com/2018/11/smarts-for-dummies.html), its sequel [Smarts for Dummies Part II ](https://baoilleach.blogspot.com/2023/02/smarts-for-dummies-part-ii.html) and the interactive [test pad](https://baoilleach.github.io/smartersmarts-js/) (requires only a web browser, JavaScript enabled).

Finally, Marvin by ChemAxon introduced [extended SMILES](https://docs.chemaxon.com/display/docs/formats_chemaxon-extended-smiles-and-smarts-cxsmiles-and-cxsmarts.md) as a format to retain additional information some programs equally can process, too (e.g. [Marvin JS](https://marvinjs-demo.chemaxon.com/latest/); [CDK depict](https://www.simolecule.com/cdkdepict/depict.html), [RDKit](https://www.rdkit.org/docs/RDKit_Book.html#cxsmiles-cxsmarts-extensions)).  As an illustration, `F\N=N/F |lp:0:3,1:1,2:1,3:3|` describes above (*Z*) isomer.

**Comment by arebruvold** [comment]
I did not think about the E-Z notation and it appears that the X is not commonly used or endorsed by IUPAC. Thank you @nbehrnd for this comprehensive answer.
