### ISSUE TITLE
Issue with Molecule Partitioning During PDB to PDBQT Conversion in Open Babel

### ISSUE THREAD

**Issue by hezhizhang-269** [openbabel/openbabel#2736]
Dear Obabel Community,

I have encountered an issue while using Open Babel to convert molecular structures from PDB to PDBQT format for docking with Vina later. It seems that during the conversion process, Open Babel is partitioning the input molecules. This behavior is unexpected, as the input files are correctly formatted and contain single, unified molecules.

Here is the command I used for the example file that I attached below:

obabel 1rpu_model1_Protein_Model_1.pdb -O 1rpu_model1_Protein_Model_1_obabel.pdbqt -xr -p 7.4 --partialcharge eem
The output file 1rpu_model1_Protein_Model_1_obabel.pdbqt contains multiple TER records. My understanding is that TER marks the end of a chain or a fragment, but in this case, it seems to indicate that molecules are being divided into separate fragments instead of remaining unified.

Could you please clarify the following:

What exactly does the presence of these excess TER records signify in this context?
Would it be appropriate to simply remove the excess TER records?
I would greatly appreciate any guidance or recommendations you could provide. 

Thank you for your attention to this matter. I look forward to your advice.

[1rpu_model1_Protein_Model_1.pdb.txt](https://github.com/user-attachments/files/18025520/1rpu_model1_Protein_Model_1.pdb.txt)
[1rpu_model1_Protein_Model_1_obabel.pdbqt.txt](https://github.com/user-attachments/files/18025521/1rpu_model1_Protein_Model_1_obabel.pdbqt.txt)

**Comment by nbehrnd** [comment]
@hezhizhang-269 I previewed the two models with Jmol (.png attached in the zip below).  Either in style `trace`, or `cartoon`, both the contents of the pdbqt file as well as the pdb is depicted as two (already) separate chains -- though this is easier to see in an interactive session. (Note the program equally provides a couple of stereographic/anaglyph projections, in case you/your group/colleagues over in crystallography have a pair of pair of glasses ([simple example](https://en.wikipedia.org/wiki/Anaglyph_3D#/media/File:Anaglyph_glasses.png)) around.)

Based on this observation, and the absence of a `-m` or `--separate`  flag in the workflow you shared, where do you observe a split of the model introduced by obabel?  Is it because e.g.,

```shell
$ grep "TER" 1rpu_model1_Protein_Model_1_obabel.pdbqt.txt -n
399:TER 
1354:TER 
```

while a similar query in the pdb doesn't yield one match?

[preview_jmol.zip](https://github.com/user-attachments/files/18060054/preview_jmol.zip)

**Comment by hezhizhang-269** [comment]
Thank you for pointing that out! After reviewing the other circumstances, I realized that the input file was always already partitioned into separate parts. I mistakenly thought obabel introduced the separation because I only noticed the TER records in the output. My apologies for the confusion—I'm still relatively new to this field.

I’m currently using obabel to convert PDB files to PDBQT format for rigid docking. Could you advise on the best way to handle multiple TER records when using the file as a receptor? Additionally, for ligands, my script currently retains only the first TER and inserts ROOT, ENDROOT, and TORSDOF 0 before and after the corresponding chunk of atoms. Should I delete the TER records in the middle, or would it be better to replace them with something like SUBROOT when using the file as a ligand?

**Comment by hezhizhang-269** [comment]
Thank you for your response and for suggesting the DataWarrior forum and resources. I’ll explore those further. I appreciate your time and insights!
