### ISSUE TITLE
OpenBabel Installation issues with Anaconda python on Mac OS X El Capitan

### ISSUE THREAD

**Issue by leelasd** [openbabel/openbabel#288]
Hi,

I am trying install openbabel with python bindings in my MAC and want to be able to use it wit anaconda python. I followed instructions from the below link. But my installation fails at the last step.

http://forums.openbabel.org/Openbabel-and-Anaconda-td4658042.html 

Any suggestions to solve this problem is highly appreciated. 

```
[100%] Building CXX object scripts/CMakeFiles/bindings_python.dir/python/openbabel-python.cpp.o
make[2]: *** No rule to make target `/Users/Sriram/anaconda/lib/libpython2.7.so', needed by `lib/_openbabel.so'.  Stop.
make[1]: *** [scripts/CMakeFiles/bindings_python.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by ghutchis** [comment]
I believe there is a conda bundle already:
https://anaconda.org/patrickfuller/openbabel <https://anaconda.org/patrickfuller/openbabel>

**Comment by leelasd** [comment]
I tried installing through conda bundle. Installation is successful but when I call the package. It gives the following error in my MAC

Fatal Python error: PyThreadState_Get: no current thread
/Users/Sriram/anaconda/bin/python.app: line 3: 20610 Abort trap: 6           /Users/Sriram/anaconda/python.app/Contents/MacOS/python "$@" 

on Linux-64 bit computer. My ipython window crashes with "Illegal Instruction" message

**Comment by leelasd** [comment]
Any suggestions on how to get the conda build work would be great.

**Comment by cstein** [comment]
Hi,

I have some pointers as to what could go wrong but I have found no solid solution to it just yet. I recently switched to Apple and have hit my head hard somethimes.

The `Fatal Python error: PyThreadState_Get: no current thread` error happens because you are using two different python versions. One to compile it and another to run it. For instance, if you compile openbabel yourself then the default mechanism is to use the python binary in `/usr/bin/python` but your default python in your path (perhaps due to anaconda or homebrew or whatever) might be `/usr/local/bin/python`. Why this happens is not totally obvious.

But yeah, basically make sure that you are using the same python version for compilation and for execution.

**Comment by EricTing** [comment]
Is you Anaconda properly installed? Did you add the Anaconda python to your `PATH`? I have `babel` and `pybel` working fine with Anaconda.

**Comment by leelasd** [comment]
Thanks @EricTing , I have /Users/Sriram/anaconda/bin in my path already. Is there anything else I am missing ?

**Comment by ghutchis** [comment]
The key is to make sure your _openbabel.so (i.e., the binary part of the Python interface) is linked against your anaconda libpython.dylib. The way to check (on Mac):

mdfind _openbabel.so
# (cd to it)
otool -L _openbabel.so

This works for me. I develop on Mac exclusively and use Anaconda. (Indeed, I'm intending to add an official anaconda package.) I'm closing this issue - if you have questions, please post to the mailing list.

**Comment by tantrev** [comment]
The latest macOS Sierra seems to not like the Openbabel v2.4.1 through Anaconda2.

Here are the [errors](http://pastebin.com/raw/EUkkR1Ei) I receive when trying to import pybel.

**Comment by cowsandmilk** [comment]
@tantrev Does installing XQuartz solve that?

https://www.xquartz.org

**Comment by tantrev** [comment]
@cowsandmilk - that fixed it, thank you!
