### ISSUE TITLE
OB Library size

### ISSUE THREAD

**Issue by mwojcikowski** [openbabel/openbabel#349]
I've just noticed that both Windows and OSX openbabel packages are less than 5MB, while Linux one is almost 50MB (talking about conda packages). Anyone has an idea why?

**Comment by baoilleach** [comment]
When the Linux one is installed, the plugins alone take up almost 120MB. Do the Windows and OSX conda packages include the underlying library or are they just the Python parts?

**Comment by mwojcikowski** [comment]
It's the binary obabel and other tools + python parts. I can see that all format files are linked in windows to one (if I remember correctly) and they seam to be highly redundant on Linux. The same (i.e small size) is on OSX. Just review the libraries in my conda packages [here](https://anaconda.org/mwojcikowski/openbabel/files). *format.so files on OSX are ~10 times smaller than Linux counterparts.

 I think it's a linker problem which might be overcome by GCC (?).

**Comment by jeffjanes** [comment]
On Tue, Oct 4, 2016 at 6:16 AM, Maciej Wójcikowski <notifications@github.com
> wrote:

> It's the binary obabel and other tools + python parts. I can see that all
> format files are linked in windows to one (if I remember correctly) and
> they seam to be highly redundant on Linux. The same (i.e small size) is on
> OSX. Just review the libraries in my conda packages here
> <https://anaconda.org/mwojcikowski/openbabel/files>. *format.so files on
> OSX are ~10 times smaller than Linux counterparts.
>
> I think it's a linker problem which might be overcome by GCC (?).
>

It would be nice to fix this on Linux (although I don't know how to).  I
don't care so much about the size, but the process startup time of obabel
can be pretty bad as it loads all those files.

Cheers,

Jeff

**Comment by baoilleach** [comment]
At the least, there should be an option to bundle the plugins into the main
.so,  independently of a static build.

On 4 Oct 2016 9:46 p.m., "Jeff Janes" <notifications@github.com> wrote:

On Tue, Oct 4, 2016 at 6:16 AM, Maciej Wójcikowski <notifications@github.com
> wrote:

> It's the binary obabel and other tools + python parts. I can see that all
> format files are linked in windows to one (if I remember correctly) and
> they seam to be highly redundant on Linux. The same (i.e small size) is on
> OSX. Just review the libraries in my conda packages here
> <https://anaconda.org/mwojcikowski/openbabel/files>. *format.so files on

> OSX are ~10 times smaller than Linux counterparts.
>
> I think it's a linker problem which might be overcome by GCC (?).
>

It would be nice to fix this on Linux (although I don't know how to). I
don't care so much about the size, but the process startup time of obabel
can be pretty bad as it loads all those files.

Cheers,

Jeff

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/openbabel/openbabel/issues/349#issuecomment-251508387>,
or mute the thread

**Comment by baoilleach** [comment]
"-DCMAKE_BUILD_TYPE=RELEASE" will fix it. It turns out that the g++ build
does not default to "RELEASE", but instead to the build that includes debug
information, hence the humungous files. I think this is a mistake and will
send a pull request. Also, the Release build should use "-O3" unless we
know there is a problem with this.

- Noel

**Comment by mwojcikowski** [comment]
Yes, indeed, that was it. I'll include that in conda packages and push them to anaconda.org.
